#!/usr/bin/env node
// Generates src/_generated/active.ts — the active icon export surface for
// @thunderstore/icons.
//
// Mode selection:
//   - "pro"          when the @fortawesome/pro-*-svg-icons packages resolve
//                    (i.e. they were installed with a FontAwesome Pro token)
//   - "placeholder"  otherwise, or when FONTAWESOME_PRO is set to 0/false/off
//
// In both modes the free solid + brand icon sets are re-exported wholesale, so
// any free icon "just works" without touching this manifest. Only the Pro icons
// listed in icons.manifest.json are handled explicitly; in placeholder mode each
// is aliased to a free-set stand-in (or faQuestion when no match exists).
//
// This file is run from the repo-root postinstall, before `preconstruct dev`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");

const manifest = JSON.parse(
  readFileSync(join(pkgRoot, "icons.manifest.json"), "utf8")
);

const envFlag = String(process.env.FONTAWESOME_PRO ?? "").toLowerCase();
const forcedOff = ["0", "false", "off", "no"].includes(envFlag);

let proResolves = false;
try {
  require.resolve("@fortawesome/pro-solid-svg-icons");
  require.resolve("@fortawesome/pro-light-svg-icons");
  proResolves = true;
} catch {
  proResolves = false;
}

const mode = !forcedOff && proResolves ? "pro" : "placeholder";

// Names actually exported by the installed free packages — used to verify
// placeholder substitutes exist, and to resolve the few names both free sets
// export (e.g. faFontAwesome, prefix), which would otherwise make `export *`
// ambiguous.
const freeSolid = require("@fortawesome/free-solid-svg-icons");
const freeBrands = require("@fortawesome/free-brands-svg-icons");
const freeNames = new Set(Object.keys(freeSolid));
const collisions = Object.keys(freeBrands).filter((n) => freeNames.has(n));
const GENERIC = freeNames.has("faQuestion") ? "faQuestion" : "faCircleQuestion";

const proNames = [...manifest.proSolid, ...manifest.proLight];

function block(names, source) {
  return `export {\n${names
    .map((n) => `  ${n}`)
    .join(",\n")},\n} from "${source}";\n`;
}

let body =
  `export * from "@fortawesome/free-solid-svg-icons";\n` +
  `export * from "@fortawesome/free-brands-svg-icons";\n`;

if (collisions.length) {
  body +=
    `// Names exported by both free sets — re-export from solid to resolve ambiguity.\n` +
    block(collisions, "@fortawesome/free-solid-svg-icons");
}

const mappings = [];
if (mode === "pro") {
  body += block(manifest.proSolid, "@fortawesome/pro-solid-svg-icons");
  if (manifest.proLight.length) {
    body += block(manifest.proLight, "@fortawesome/pro-light-svg-icons");
  }
} else {
  const lines = [];
  for (const name of proNames) {
    const candidates = manifest.substitutes[name] ?? [];
    const picked = candidates.find((c) => freeNames.has(c)) ?? GENERIC;
    mappings.push(`${name} -> ${picked}`);
    lines.push(picked === name ? `  ${name}` : `  ${picked} as ${name}`);
  }
  body += `export {\n${lines.join(
    ",\n"
  )},\n} from "@fortawesome/free-solid-svg-icons";\n`;
}

const header =
  `// AUTO-GENERATED by scripts/generate-icons.mjs — DO NOT EDIT.\n` +
  `// Mode: ${mode}. Regenerated on every \`pnpm install\` (repo-root postinstall).\n` +
  `// To force placeholders even with Pro installed: FONTAWESOME_PRO=0 pnpm --filter @thunderstore/icons run generate\n` +
  `/* eslint-disable */\n`;

const outDir = join(pkgRoot, "src", "_generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "active.ts"), `${header}\n${body}`, "utf8");

console.log(`[@thunderstore/icons] generated active.ts in "${mode}" mode.`);
if (mode === "placeholder") {
  console.log(
    `[@thunderstore/icons] Pro icons not installed — using free-set placeholders:`
  );
  for (const m of mappings) console.log(`    ${m}`);
}
