name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  get-node-version:
    name: Get Node version
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.base.repo.id != github.event.head.repo.id)
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.get-node-version.outputs.node-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Check get-node-version version
        uses: ./.github/actions/get-node-version
        with:
          package-json: .github/actions/get-node-version/package.json
      - name: Get Node version
        id: get-node-version
        uses: ./.github/actions/get-node-version

  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    needs: get-node-version
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
      - name: Setup Python 3.8
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-in-project: true
      - name: Cache poetry venv
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: .venv
          key: "poetry-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('poetry.lock') }}"
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install poetry dependencies
        run: poetry install
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - name: Install pnpm dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Cache pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: "pre-commit-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ needs.get-node-version.outputs.node-version }}-\
            ${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: Run pre-commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

#  TODO: Configure build secrets & re-enable
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v5
#      - name: Build Docker images
#        run: IMAGE_TAG=${GITHUB_REF##*/} docker compose -f docker-compose.build.yml build --pull
#      - name: Login to Docker Hub
#        if: github.event_name != 'pull_request'
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
#        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#      - name: Push image to Docker Hub
#        if: github.event_name != 'pull_request'
#        run: IMAGE_TAG=${GITHUB_REF##*/} docker compose -f docker-compose.build.yml push

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [get-node-version, pre-commit]
    env:
      VITE_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
      VITE_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      VITE_AUTH_BASE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
      VITE_AUTH_RETURN_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Setup Node ${{ needs.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
          cache: "pnpm"
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Build @thunderstore/typed-event-emitter
        run: pnpm --filter @thunderstore/typed-event-emitter run build
      - name: Build @thunderstore/thunderstore-api
        run: pnpm --filter @thunderstore/thunderstore-api run build
      - name: Build @thunderstore/use-promise
        run: pnpm --filter @thunderstore/use-promise run build
      - name: Build @thunderstore/react-dnd
        run: pnpm --filter @thunderstore/react-dnd run build
      - name: Build @thunderstore/graph-system
        run: pnpm --filter @thunderstore/graph-system run build
      - name: Build @thunderstore/dapper
        run: pnpm --filter @thunderstore/dapper run build
      - name: Build @thunderstore/cyberstorm-theme
        run: pnpm --filter @thunderstore/cyberstorm-theme run build
      - name: Build @thunderstore/ts-uploader
        run: pnpm --filter @thunderstore/ts-uploader run build
      - name: Build @thunderstore/ts-uploader-react
        run: pnpm --filter @thunderstore/ts-uploader-react run build
      - name: Build @thunderstore/cyberstorm
        run: pnpm --filter @thunderstore/cyberstorm run build
      - name: Build @thunderstore/cyberstorm-forms
        run: pnpm --filter @thunderstore/cyberstorm-forms run build
      - name: Build @thunderstore/dapper-ts
        run: pnpm --filter @thunderstore/dapper-ts run build
      - name: Build @thunderstore/dapper-fake
        run: pnpm --filter @thunderstore/dapper-fake run build
      - name: Build @thunderstore/ts-api-react
        run: pnpm --filter @thunderstore/ts-api-react run build
      - name: Build @thunderstore/ts-api-react-actions
        run: pnpm --filter @thunderstore/ts-api-react-actions run build
      - name: Build @thunderstore/ts-api-react-forms
        run: pnpm --filter @thunderstore/ts-api-react-forms run build
      - name: Typecheck @thunderstore/cyberstorm-remix
        run: pnpm --filter @thunderstore/cyberstorm-remix run typecheck
      - name: Build @thunderstore/cyberstorm-remix
        run: pnpm --filter @thunderstore/cyberstorm-remix run build
      - name: Build @thunderstore/storybook
        run: pnpm --filter @thunderstore/storybook run build

  test:
    name: Test
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: [get-node-version, pre-commit, build]
    env:
      VITE_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
      VITE_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      VITE_AUTH_BASE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
      VITE_AUTH_RETURN_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Setup Python 3.10"
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: pnpm/action-setup@v4
      - name: Setup Node ${{ needs.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
          cache: "pnpm"
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache poetry venv
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: tools/test-ci/.venv
          key: "poetry-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('tools/test-ci/poetry.lock') }}"
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install poetry dependencies
        run: |
          cd tools/test-ci/
          poetry install
      - name: Run testing script
        run: |
          cd tools/test-ci/
          poetry run python run_ci_script.py
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: [get-node-version, pre-commit, build, test]
    strategy:
      matrix:
        projects: [
          { dir: "apps/storybook", token: "CHROMATIC_CYBERSTORM_TOKEN" },
        ]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Setup Node ${{ needs.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
          cache: "pnpm"
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Build dependencies
        run: pnpm run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets[matrix.projects.token] }}
          workingDir: ${{ matrix.projects.dir }}
          exitOnceUploaded: true
