name: Thunderstore UI - Tag

on:
  push:
    tags:
      - '*'
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        env:
          GH_TOKEN: ${{ secrets.THUNDERSTORE_BOT_PAT }}
        run: |
          gh workflow run build-thunderstore-ui-tag.yml \
          --repo Riskidev/Infra-v2 \
          --ref master \
          -f tag_name=${{ github.ref_name }} \
          -f repo_url=${{ github.repository }}
