name: Thunderstore UI - Release

on:
  release:
    types: [released]
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        uses: BeewiseTechnologiesLTD/remote-workflow-trigger@v1
        id: trigger
        with:
          github_token: ${{ secrets.THUNDERSTORE_BOT_PAT }}
          workflow_id: 'build-thunderstore-ui-release.yml'
          target_repo: 'Riskidev/Infra-v2'
          ref: 'infra-v2-prod'
          inputs: '{"tag_name": "${{ github.event.release.tag_name }}", "repo_url": "${{ github.repository }}"}'
          wait_interval: '10'
          timeout: '900'
      
      - name: Outputs
        run: |
          echo "Workflow ID: ${{ steps.trigger.outputs.run_id }}"
          echo "Workflow URL: ${{ steps.trigger.outputs.workflow_url }}"
          echo "Status: ${{ steps.trigger.outputs.status }}"
          echo "Conclusion: ${{ steps.trigger.outputs.conclusion }}"