name: Thunderstore UI - Released
on:
  release:
    types: [released]
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        env:
          GH_TOKEN: ${{ secrets.THUNDERSTORE_BOT_PAT }}
        run: |
          gh workflow run build-thunderstore-ui-release.yml \
          --repo Riskidev/Infra-v2 \
          --ref master \
          -f tag_name='${{ github.event.release.tag_name }}'
