name: "Visual diff"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  get-node-version:
    name: Get Node version
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.get-node-version.outputs.node-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Check get-node-version version
        uses: ./.github/actions/get-node-version
        with:
          package-json: .github/actions/get-node-version/package.json
      - name: Get Node version
        id: get-node-version
        uses: ./.github/actions/get-node-version
  visual-diff:
    name: "Generate visual diffs"
    runs-on: "ubuntu-latest"
    needs: get-node-version
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Python 3.10"
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache poetry venv
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: tools/visual-diff-ci/.venv
          key: "poetry-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('tools/visual-diff-ci/poetry.lock') }}"
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install poetry dependencies
        run: |
          cd tools/visual-diff-ci/
          poetry install
      - name: Run visual diffing script
        run: |
          cd tools/visual-diff-ci/
          poetry run python run_ci_script.py
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
